export const categories = [
  {
    title: "all",
    label: "all",
    tag: "all",
    name: "all",
  },
  {
    title: "skincare",
    label: "skincare",
    tag: "skincare",
    name: "skincare",
  },
  {
    title: "parfume",
    label: "Parfume",
    tag: "parfume",
    name: "Parfume",
  },
  {
    title: "ibu & Bayi",
    label: "PeralatanBayi",
    tag: "peralatanBayi",
    name: "peralatanBayi",
  },
  {
    title: "baju Dewasa",
    label: "bajuDewasa",
    tag: "bajuDewasa",
    name: "bajuDewasa",
  },
  {
    title: "alat Kebersihan",
    label: "alatKebersihan",
    tag: "alatKebersihan",
    name: "alatKebersihan",
  },
  {
    title: "special Diskon",
    label: "SpecialDiscount",
    tag: "specialDiskon",
    name: "SpecialDiscount",
  },
  {
    title: "baju Anak",
    label: "bajuAnakanak",
    tag: "bajuAnak",
    name: "bajuAnakanak",
  },
  {
    title: "laundry",
    label: "laundry",
    tag: "laundry",
    name: "laundry",
  },
  {
    title: "kesehatan",
    label: "kesehatan",
    tag: "kesehatan",
    name: "kesehatan",
  },
  {
    title: "alat Masak",
    label: "alatMasak",
    tag: "alatMasak",
    name: "alatMasak",
  },
  {
    title: "outdoors",
    label: "outdoors",
    tag: "outdoors",
    name: "outdoors",
  },
  {
    title: "alat Pancing",
    label: "AlatPancing",
    tag: "alatPancing",
    name: "AlatPancing",
  },
  {
    title: "tas Wanita",
    label: "TasWanita",
    tag: "tasWanita",
    name: "TasWanita",
  },
  {
    title: "gudang",
    label: "gudang",
    tag: "gudang",
    name: "gudang",
  },
];
