import { all, baby, clean, discount, fishing, gudang, healty, laundry, masak, outdoor, parfume, shirt, shirtKid, skincare, womenBag } from "../public/assets";

export const categories = [
  {
    title: "all",
    label: "all",
    tag: "all",
    name: "all",
    icon: all,
  },
  {
    title: "skincare",
    label: "skincare",
    tag: "skincare",
    name: "skincare",
    icon: skincare,
  },
  {
    title: "parfume",
    label: "Parfume",
    tag: "parfume",
    name: "Parfume",
    icon: parfume,
  },
  {
    title: "ibu & Bayi",
    label: "PeralatanBayi",
    tag: "peralatanBayi",
    name: "peralatanBayi",
    icon: baby,
  },
  {
    title: "baju Dewasa",
    label: "bajuDewasa",
    tag: "bajuDewasa",
    name: "bajuDewasa",
    icon: shirt,
  },
  {
    title: "alat Kebersihan",
    label: "alatKebersihan",
    tag: "alatKebersihan",
    name: "alatKebersihan",
    icon: clean,
  },
  {
    title: "special Diskon",
    label: "SpecialDiscount",
    tag: "specialDiskon",
    name: "SpecialDiscount",
    icon: discount,
  },
  {
    title: "baju Anak-anak",
    label: "bajuAnakanak",
    tag: "bajuAnak",
    name: "bajuAnakanak",
    icon: shirtKid,
  },
  {
    title: "laundry",
    label: "laundry",
    tag: "laundry",
    name: "laundry",
    icon: laundry,
  },
  {
    title: "kesehatan",
    label: "kesehatan",
    tag: "kesehatan",
    name: "kesehatan",
    icon: healty,
  },
  {
    title: "peralatan Masak",
    label: "alatMasak",
    tag: "alatMasak",
    name: "alatMasak",
    icon: masak,
  },
  {
    title: "outdoors",
    label: "outdoors",
    tag: "outdoors",
    name: "outdoors",
    icon: outdoor,
  },
  {
    title: "alat Pancing",
    label: "AlatPancing",
    tag: "alatPancing",
    name: "AlatPancing",
    icon: fishing,
  },
  {
    title: "tas Wanita",
    label: "TasWanita",
    tag: "tasWanita",
    name: "TasWanita",
    icon: womenBag,
  },
  {
    title: "gudang",
    label: "gudang",
    tag: "gudang",
    name: "gudang",
    icon: gudang,
  },
];
